apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord-alerts
  namespace: flux-system
spec:
  type: discord
  channel: fluxcd-alerts
  secretRef:
    name: discord-url