---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: '>=v1.8.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true